workflows:
  build_debug:
    name: Build Debug APK
    environment:
      vars:
        # Optionally set GROQ_API_KEY here as encrypted env var in Codemagic UI
        # GROQ_API_KEY: Encrypted(value)
    scripts:
      - name: Checkout
        script: |
          echo "Starting build for HackerNb (debug)"
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug
      - name: Post-build message
        script: |
          echo "✅ Build sukses! Unduh APK HackerNb kamu di tab Artifacts (app/build/outputs/apk/debug/app-debug.apk)"
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
