workflows:
  build_debug:
    name: Build Debug APK
    scripts:
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
